import os

DEBUG = False
TEMPLATE_DEBUG = DEBUG

if False not in ( 'STATIC_URL', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_STORAGE_BUCKET_NAME' in os.environ ):
	STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
	STATIC_URL = os.environ['STATIC_URL']
	AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
	AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
	AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']